### ISSUE TITLE
How can I get connection string for RedisJson from Tye?

### ISSUE THREAD

**Issue by spicycoder** [redis/redis-om-dotnet#45]
I am trying to setup redis json instance using the docker image `redislabs/rejson` 
In my ASP.NET 6 Project, it works fine

If I try to replace the connection string from `appsettings.json` to `tye.yaml`, The connection string is empty

`tye.yaml`

```yaml
name: superheroes
services:
  - name: bookofheroes
    project: BookOfHeroes/BookOfHeroes.csproj
  - name: redis
    image: redislabs/rejson
    bindings:
      - port: 6379
        connectionString: "${host}:${port}"
```

`Program.cs`

```cs
builder.Services.AddSingleton(_ =>
    new RedisConnectionProvider(builder.Configuration.GetConnectionString("redis")));
```

This errors out, as it is unable to fetch the connection string when using `tye run`

Related: https://github.com/dotnet/tye/issues/1271
